# Sync shared packages into app addons (D4).
param(
	[ValidateSet("all", "game", "map_editor")]
	[string]$App = "all"
)

$ErrorActionPreference = "Stop"
$Root = Resolve-Path (Join-Path $PSScriptRoot "../..")
Set-Location $Root

$maps = @(
	@{ Pkg = "foundation"; Sources = @("packages/foundation") },
	@{ Pkg = "content"; Sources = @("packages/content", "scripts/content") },
	@{ Pkg = "map"; Sources = @("packages/map") },
	@{ Pkg = "gameplay"; Sources = @("packages/gameplay", "game/match", "game/entities", "game/features") }
)

function Sync-OneApp([string]$AppName) {
	$appRoot = Join-Path $Root "apps/$AppName"
	if (-not (Test-Path $appRoot)) {
		Write-Error "Missing app: $appRoot"
	}
	$addons = Join-Path $appRoot "addons"
	New-Item -ItemType Directory -Force -Path $addons | Out-Null
	foreach ($m in $maps) {
		$dest = Join-Path $addons ("rts_" + $m.Pkg)
		if (Test-Path $dest) {
			Remove-Item -Recurse -Force $dest
		}
		New-Item -ItemType Directory -Force -Path $dest | Out-Null
		$hasher = [System.Security.Cryptography.SHA256]::Create()
		$allBytes = New-Object System.Collections.Generic.List[byte]
		foreach ($srcRel in $m.Sources) {
			$src = Join-Path $Root $srcRel
			if (-not (Test-Path $src)) { continue }
			$leaf = Split-Path $srcRel -Leaf
			$target = Join-Path $dest $leaf
			Copy-Item -Recurse -Force $src $target
			Get-ChildItem -Recurse -File $target | ForEach-Object {
				$bytes = [System.IO.File]::ReadAllBytes($_.FullName)
				$allBytes.AddRange($bytes)
			}
		}
		$hash = [BitConverter]::ToString($hasher.ComputeHash($allBytes.ToArray())).Replace("-", "").ToLowerInvariant()
		Set-Content -Path (Join-Path $dest ".sync-hash") -Value $hash -Encoding utf8
		# Prevent editing generated tree
		Set-Content -Path (Join-Path $dest "DO_NOT_EDIT.txt") -Value "Generated by Sync-Packages.ps1. Edit packages/ or source trees instead." -Encoding utf8
		Write-Host "Synced rts_$($m.Pkg) -> apps/$AppName/addons (hash=$($hash.Substring(0,12))…)"
	}
}

$apps = if ($App -eq "all") { @("game", "map_editor") } else { @($App) }
foreach ($a in $apps) { Sync-OneApp $a }
Write-Host "Done."
